### ISSUE TITLE
Multi-sample support and statistics

### ISSUE THREAD

**Issue by marcelm** [rhpvorderman/sequali#94]
I’m forwarding a suggestion by @ianm0001, who would like to be able to run sequali on multiple input files. She would be interested in some statistics across samples:

> - Read length distribution per sample
> - No. of reads per sample
> - Average read quality score per sample (not base or read - across all reads in a sample)
> - Length range
> 
> The only quality indicator across the entire sample in sequali is currently the Q20 figure, but if I could forward a wish it would be to have the average read quality score per sample, not just in the multi-sample function but also when running sequali on single samples :)

**Comment by rhpvorderman** [comment]
Would integrating sequali with MultiQC solve that problem? #86 

That is on my to-do list (most likely for the holiday).

**Comment by rhpvorderman** [comment]
> Yes, something like MultiQC but compatible with Nanopore sequencing data would be really helpful. For now I have solved the problem by merging all the reads in each library and running sequali on that merged file, to be able to see stats for several reads at once, but of course then I can’t compare between samples. I have also run sequali individually on each of my 141 samples, which of course works, but having a multi-feature would be great (also for others who will be engaged in similar projects as mine) :)

This sounds like an excellent role for MultiQC, since it already has the comparison between samples code. The reason sequali also outputs JSON is that I am looking to integrate it with MultiQC in the future. That will be quite a lot of work however, so I doubt I will be able to do this before the holiday.

The great advantage of MultiQC is that it can also integrate reports of other tools such as cutadapt, so people who are engaged in similar projects can just run MultiQC once and be done with it. 

> And again, a super useful feature for the single / multiple version would be to get an average Q score for each sample, i.e. across all samples. In my opinion, this would be much more useful than the Q20 reads figure :)

Averaging Q scores is really hard. Because it is a logarithmic score based on the error rate. In this case, should longer reads weigh heavier, because they represent more bases? That would require some rewriting as sequali does not currently keep the length and quality information together. Even at the base level it is compressed into 12 categories (instead of 93 distinct Q values). 

The reason for this data compression is speed. Nanopore reads are so long and having such disparate lenghts, that the resulting count tables in the application will get quite large as well. By only recording what is strictly required to get a good overview, sequali can be quite fast. (It processes 250.000.000 bases per second on my laptop.) 

What I can easily do with the information I currently gather is to make a per read quality distribution table the same as the length distribution. You can then easily look if you want to know the lower or higher 1%/5%/10% bounds on the Q Score for each sample while also giving the median (N50). That would probably be more informative than just the mean, as it indicates the spread a little better.

What are your thoughts on this?

**Comment by rhpvorderman** [comment]
I have added a small table for the read quality score distribution:

![Persequenceaveragequalitscores](https://github.com/rhpvorderman/sequali/assets/26142226/cbc22d96-5423-43d5-829a-131885b40f18)

Would this be sufficient for your use cases?

MultiQC has a module for sequali now, but the new version that has this still needs to be released.

**Comment by ianm0001** [comment]
Excellent, thank you! :)
